### PR TITLE
add a launch configuration files and adjust the layout of examples

### PR DESCRIPTION
**Pull request by mazkatli**
see [Palladio-452](https://palladio-simulator.atlassian.net/browse/PALLADIO-452) and  [Palladio-528](https://palladio-simulator.atlassian.net/browse/PALLADIO-528)

### CODE REVIEW

**Review by seiferma — CHANGES_REQUESTED** [review]
I opened the projects with the latest drop on Linux and Windows and got broken usage model diagrams (PALLADIO-528) in
* AcquireExample
* ConnectedHeating
* HardDiskModel
* HDD Demo
* HDD Patch Demo
* InfrastructureComponent_Example
* LinkingResourceTest
* Minimum_Project
* MinimumEventExample
* PCMSetVariableExample
* ReliabilityTest
* ReplicatedCompositeComponentExample
* Simple Tactics Example
* SubsystemTest

Additionally, some projects do not have diagrams at all
* Minimum_ExactScheduler_Project

I did not check all SimuLizar configurations but just picked the InfrastructureComponent_Example that has no SimuLizar launch config. I created one with the minimal inputs and got some results. I do not know if these results are somehow useful but all projects supported by SimuLizar should have a launch config according to PALLADIO-452.

**Review by seiferma — CHANGES_REQUESTED** [review]
There are still broken usage model diagrams:
* InfrastructureComponent_Example
* Simple Tactics Example (quickbooking)
* SubsystemTest (default, nestedSubSystem, subsystemInstantiatedTwice)

No usage model diagrams:
* Minimum_ExactScheduler_Project
* ScreencastMediaStore (MediaStoreEnqueueDownloadCache, MediaStoreInstant-DownloadCache)
* Simple Optimisation Example (default_c4, newWithComposites -> need migration before diagram creation)

Launch configs:
* HDD Demo: contains Minimum_Project_Example-Simulizar.launch
* PCMForkExample: contains two identical launch configs with same name
* ReliabilityTest: uses deprecated SensorFramework instead of EDP2, launch config does not work. We should delete the launch config until [PALLADIO-526](https://palladio-simulator.atlassian.net/browse/PALLADIO-526) is solved.
* Simple Optimisation Example: SimpleOptimisation_Example-WithComposites-Simulizar.launch leads to failed simulation (models need migration first)
* Simple Tactics Example: why is the launch config named SimpleHeuristicsExample_Example-simulizar.launch?

**Comment by mazkatli** [comment]
The requested changes are done.
Just the simulation of the Simple Optimisation Example (SimpleOptimisation_Example-WithComposites-Simulizar.launch) is still failed. The models are broken.

**Review by seiferma — CHANGES_REQUESTED** [review]
I fixed the models of the SimpleOptimisation Example. Changes look good now except for one thing:

The Minimum_ExactScheduler_Project contains an old GMF diagram to visualize the usage model. The old editors are deprecated and we should **not** ship diagrams for these editors anymore. Please delete this diagram.

There are two options to proceed afterwards:
* Convert the project to a modeling project and create Sirius diagrams for these models.
* The issue does not explicitly request creating graphical representations for all example models. Therefore, you can also decide to not do this. In that case, please file a new issue in JIRA to convert this example to a proper modeling project and merge the pull request.

**Comment by mazkatli** [comment]
I delete the old GMF diagram from Minimum_ExactScheduler_Project and created new graphical Sirius representations for all example models.

**Review by seiferma — APPROVED** [review]
Looks good to me.

**Pull request merged**
